### PR TITLE
support new token format

### PR DESCRIPTION
**Pull request by obstructive**

### CODE REVIEW

**Comment by masterjanic** [comment]
Hello and thank you for your pull request. Could you please provide an explanation on why you think this change is mandatory? 

I did not check whether there are new token formats. If thats the case, please provide samples. Then I can confirm the change.

**Comment by obstructive** [comment]
> Hello and thank you for your pull request. Could you please provide an explanation on why you think this change is mandatory?
> 
> I did not check whether there are new token formats. If thats the case, please provide samples. Then I can confirm the change.

supports new tokens that start with "MT" (same as 2015-2016), a example token: `MTEwNzU4MTkwMDU2ODE1MDA0Nw.GvbQdu.pJFhdN8KrkZVBq_tF-omGHgYqCLOiQuvtf2ibM` (disabled btw)

**Comment by obstructive** [comment]
> I can merge your request, but please keep the old syntax with \w since its the short form of A-Za-z0-9

it don't works for the token somewhy

**Comment by masterjanic** [comment]
I have closed your pull request since I updated the whole project. I also implemented the new regex, thank you for the information!

**Pull request closed without merging**
